server:
  port: 6001

spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 40
#        max-idle: 20
#        min-idle: 15
#        max-wait: 5000
#  data:
#    redis:
#      host: d6c-test-internal.redis.rds.aliyuncs.com
#      port: 6379
#      username: haolink
#      password: Admin12345haolinkTest